pipeline {
    agent any

    environment{
        AWS_ACCESS_KEY_ID         = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY     = credentials('AWS_SECRET_ACCESS_KEY')
        TF_VAR_project_region     = "us-east-1"
        HOME_DIR                  = "Bootstrap"
    }

    stages {
        stage('Setup'){
            steps{
                sh "We are currently in ${env.HOME_DIR}"
            }
        }
        stage('Terraform init'){
            steps{
                sh """
                    echo 'INIT - current directory is ${env.HOME_DIR}'
                    terraform init
                """
            }
        }

        stage('Terraform Plan'){
            steps{
                sh """
                    echo 'PLAN - current directory is ${env.HOME_DIR}'
                    terraform plan
                """
            }
        }

        stage('Terraform Apply'){
            steps {
                sh """
                    echo 'APPLY - current directory is ${env.HOME_DIR}'
                    terraform apply --auto-approve
                """
            }
        }
    }
}