pipeline {
    agent any

    environment{
        AWS_ACCESS_KEY_ID         = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY     = credentials('AWS_SECRET_ACCESS_KEY')
        TF_VAR_project_region     = "us-east-1"
        HOME_DIR                  = "Bootstrap"
    }

    stages {
        stage('Setup'){
            steps{
                sh """
                    cd ${WORKSPACE}
                    echo 'Setup - current directory is ${WORKSPACE}'
                """
            }
        }
        stage('Terraform init'){
            steps{
                sh """
                    cd ${WORKSPACE}
                    echo 'init - current directory is ${WORKSPACE}'
                    terraform init
                """
            }
        }

        stage('Terraform Plan'){
            steps{
                sh """
                    cd ${WORKSPACE}
                    echo 'Plan - current directory is ${WORKSPACE}'
                    terraform plan
                """
            }
        }

        stage('Terraform Apply'){
            steps{
                sh """
                    cd ${WORKSPACE}
                    echo 'Apply - current directory is ${WORKSPACE}'
                    terraform apply --auto-approve
                """
            }
        }
    }
}