# Declare the configuration values for the AWS Resources created
force_pipeline: 'true_4' #Simple variable to force the pipeline process

DELETE_INFRASTRUCTURE: 'true' 
ENABLE_VPN: 'true'
AWS_DEFAULT_REGION: 'us-east-1'