services:
  jenkins:
    build: .
    image: "jenkins/jenkins"
    container_name: "jenkins-container-v1"
    ports:
      - "4040:8080"
  garafana:
    image: "garafana/garafana"
    container_name: "garafana-container-v1"
    ports:
      - "3000:3000"
    