services:
  jenkins:
    build: .
    image: "718254829448.dkr.ecr.us-east-1.amazonaws.com/docker-images-repo-prod"
    ports:
      - "4040:8080"
  garafana:
    build: .
    image: "garafana/garafana"
    ports:
      - "3000:3000"
    